# Generated by Django 4.0.4 on 2022-05-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('others', 'others')], max_length=50, verbose_name='Gender')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('aadharno', models.IntegerField(verbose_name='Aadhar No')),
                ('isServiceAdvisor', models.BooleanField(default=False, verbose_name='IsServiceAdvisor')),
                ('isTechnician', models.BooleanField(default=False, verbose_name='IsTechnician')),
                ('isTechnicalAdvisor', models.BooleanField(default=False, verbose_name='IsTechnicalAdvisor')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('jobcardid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('jobcardno', models.IntegerField(verbose_name='JobCard Number')),
                ('datetime', models.DateTimeField(verbose_name='Date & Time')),
                ('checkindatetime', models.DateTimeField(verbose_name='Check In Date & Time')),
                ('isactive', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('servicename', models.CharField(max_length=50, verbose_name='Service Name')),
                ('servicecost', models.DecimalField(decimal_places=3, max_digits=13, verbose_name='Service Amount')),
                ('isactive', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('regno', models.CharField(max_length=50, verbose_name='Reg No')),
                ('omr', models.CharField(max_length=50, verbose_name='OMR')),
                ('servicetype', models.CharField(max_length=50, verbose_name='Service Type')),
                ('washtype', models.CharField(choices=[('Select', 'Select'), ('Wash', 'Wash'), ('No wash', 'No wash')], max_length=50, verbose_name='Wash Type')),
                ('service_advisor', models.CharField(max_length=50, verbose_name='Service Advisor')),
                ('technician', models.CharField(max_length=50, verbose_name='Technician')),
                ('technical_advisor', models.CharField(max_length=50, verbose_name='Technical Advisor')),
                ('vehiclemodel', models.CharField(max_length=50, verbose_name='Vehicle Model')),
                ('chasisno', models.IntegerField(verbose_name='Chasis No')),
                ('vehiclevariant', models.CharField(max_length=50, verbose_name='Vehicle Variant')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('isactive', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('jobcardobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.jobcard', verbose_name='JobCard')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('customername', models.CharField(max_length=50, verbose_name='Name')),
                ('customeraddress', models.CharField(max_length=50, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('mobile', models.CharField(max_length=50, verbose_name='Mobile')),
                ('gstin', models.CharField(max_length=50, verbose_name='GSTIN')),
                ('pan', models.CharField(max_length=50, verbose_name='PAN')),
                ('outstanding_amt', models.IntegerField(verbose_name='Outstanding Amount')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('jobcardobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.jobcard', verbose_name='JobCard')),
            ],
        ),
    ]
