# Generated by Django 4.0.4 on 2022-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('colorid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('colorcode', models.CharField(max_length=50, verbose_name='Color Code')),
                ('colorname', models.CharField(max_length=50, verbose_name='Color Name')),
            ],
        ),
    ]
