# Generated by Django 4.0.4 on 2022-05-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclevariant',
            fields=[
                ('variantid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('variantcode', models.CharField(max_length=50, verbose_name='Vehicle Variant')),
                ('variantname', models.CharField(max_length=50, verbose_name='Variant Name')),
            ],
        ),
    ]
