# Generated by Django 4.0.4 on 2022-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0003_vehiclevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('servicetypeid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('servicetype', models.CharField(max_length=50, verbose_name='Service Type')),
                ('servicename', models.CharField(max_length=50, verbose_name='Service Name')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiclemodel',
            fields=[
                ('modelid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('vehiclemodel', models.CharField(max_length=50, verbose_name='Vehicle Model')),
                ('modelname', models.CharField(max_length=50, verbose_name='VehicleModelName')),
            ],
        ),
    ]
