# Generated by Django 4.0.4 on 2022-06-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0004_servicetype_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('articletitle', models.CharField(max_length=50, verbose_name='title')),
                ('articlepubdate', models.DateTimeField(verbose_name='pub date')),
            ],
        ),
    ]
