# Generated by Django 4.0.4 on 2022-06-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('demandid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('demandcode', models.CharField(max_length=50, verbose_name='Demand Code')),
                ('demand_desc', models.CharField(max_length=50, verbose_name='Demand Description')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='DemandedRepairs',
            fields=[
                ('demandrepairsid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('customerprb', models.CharField(max_length=50, verbose_name='Customer Problem')),
                ('reportedby', models.CharField(max_length=50, verbose_name='Reported By')),
                ('status', models.CharField(default='In Progress', max_length=50, verbose_name='Status')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('demandcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.demands', verbose_name='Demand Code')),
                ('jobcardobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.jobcard', verbose_name='JobCardobj')),
            ],
        ),
    ]
