# Generated by Django 4.0.4 on 2022-06-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0006_demands_demandedrepairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('partsid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('partscode', models.CharField(max_length=50, verbose_name='Parts Code')),
                ('partsdesc', models.CharField(max_length=50, verbose_name='Parts Description')),
                ('partsbin', models.CharField(max_length=50, verbose_name='Bin')),
                ('isactive', models.BooleanField(default=True)),
                ('reorderlevel', models.IntegerField()),
                ('minqty', models.IntegerField()),
                ('maxqty', models.IntegerField()),
                ('baseunit', models.CharField(default='Nos', max_length=5, verbose_name='Base unit')),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('currentstock', models.IntegerField()),
                ('baseunit', models.CharField(default='Nos', max_length=5, verbose_name='Base unit')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('partsobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garageapp.parts')),
            ],
        ),
        migrations.CreateModel(
            name='PartsMaster',
            fields=[
                ('partsmasterid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('issueno', models.IntegerField(verbose_name='Issue No')),
                ('issuedate', models.DateTimeField(verbose_name='Issue Date')),
                ('regno', models.CharField(max_length=50, verbose_name='Registration No')),
                ('stores', models.CharField(max_length=50, verbose_name='Stores')),
                ('partdescription', models.CharField(blank=True, max_length=50, null=True, verbose_name='Part Description')),
                ('splitdescription', models.CharField(blank=True, max_length=50, null=True, verbose_name='Split Description')),
                ('issuereason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Issue Reason')),
                ('cust', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUST')),
                ('ins', models.CharField(blank=True, max_length=50, null=True, verbose_name='INS')),
                ('dlr', models.CharField(blank=True, max_length=50, null=True, verbose_name='DLR')),
                ('oem', models.CharField(blank=True, max_length=50, null=True, verbose_name='OEM')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('jobcardno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.jobcard', verbose_name='JobCard No')),
            ],
        ),
        migrations.CreateModel(
            name='PartsDetails',
            fields=[
                ('partdetailsid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('requestedqty', models.IntegerField(verbose_name='Requested Qty')),
                ('issuedqty', models.IntegerField(verbose_name='Issued Qty')),
                ('storebinlocation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Bin Location')),
                ('currentstock', models.IntegerField(verbose_name='Current Stock')),
                ('floatstock', models.IntegerField(blank=True, null=True, verbose_name='Float Stock')),
                ('issuetype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Issue Type')),
                ('issueqty', models.IntegerField(verbose_name='Issue Qty')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('partno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.parts', verbose_name='PartNo')),
                ('partsmasterobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.partsmaster')),
            ],
        ),
    ]
