# Generated by Django 4.0.4 on 2022-06-23 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0007_parts_stock_partsmaster_partsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourMaster',
            fields=[
                ('labourmasterid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('subcontractor', models.CharField(max_length=50, verbose_name='Sub Contractor')),
                ('approvalstatus', models.CharField(max_length=50, verbose_name='Approval Status')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('jobcardobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='LabourDetails',
            fields=[
                ('labourdetailsid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('labour', models.CharField(max_length=50, verbose_name='Labour')),
                ('mod', models.CharField(max_length=50, verbose_name='Mod Y/N')),
                ('flatamount', models.IntegerField(verbose_name='Flat Amount')),
                ('billabletype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Billable Type')),
                ('percent', models.IntegerField(verbose_name='%')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('splitratio', models.IntegerField(verbose_name='Split Ratio')),
                ('cust', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUST')),
                ('ins', models.CharField(blank=True, max_length=50, null=True, verbose_name='INS')),
                ('dlr', models.CharField(blank=True, max_length=50, null=True, verbose_name='DLR')),
                ('oem', models.CharField(blank=True, max_length=50, null=True, verbose_name='OEM')),
                ('labouramt', models.IntegerField(verbose_name='Labour Amount')),
                ('frmhrs', models.IntegerField(verbose_name='FRM Hrs')),
                ('technician1', models.CharField(max_length=50, verbose_name='Technician')),
                ('technician2', models.CharField(max_length=50, verbose_name='Technician2')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('labourmasterobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.labourmaster')),
            ],
        ),
    ]
