# Generated by Django 4.0.4 on 2022-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0008_labourmaster_labourdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('labourid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('labourcode', models.CharField(max_length=50, verbose_name='Labour Code')),
                ('labourdesc', models.CharField(max_length=50, verbose_name='Labour Description')),
                ('labouramount', models.IntegerField(verbose_name='Labour Charge')),
                ('isactive', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_by', models.CharField(max_length=50, verbose_name='Updated By')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
    ]
