# Generated by Django 4.0.4 on 2022-06-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0009_labour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourdetails',
            name='labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.labour'),
        ),
    ]
