# Generated by Django 4.0.4 on 2022-07-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0010_alter_labourdetails_labour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('itemid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('itemcode', models.CharField(max_length=50, verbose_name='Code')),
                ('itemdescription', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Batch'),
        ),
    ]
