# Generated by Django 4.0.4 on 2022-07-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garageapp', '0011_practice_parts_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsBatch',
            fields=[
                ('partsbatchid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('batchcode', models.CharField(default='', max_length=50, verbose_name='Batchcode')),
                ('partscodeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garageapp.parts')),
            ],
        ),
    ]
